name: tptaq_bms_util_module
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  convert: ^3.0.0
  cupertino_icons: ^1.0.2
  decimal: ^2.3.3
  flutter:
    sdk: flutter
    
  
  
  plugin_platform_interface: ^2.1.5
  tptaq_bms_util_plugin:
    path: tptaq_bms_util_plugin

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.tp.tptaq_bms_util_module
    iosBundleIdentifier: com.tp.tptaq_bms_util_module
